// <auto-generated />
using System;
using Eatech.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eatech.Migrations
{
    [DbContext(typeof(ContextoBD))]
    [Migration("20240623060759_bdfinalv13")]
    partial class bdfinalv13
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Eatech.Models.Bd_Alumno", b =>
                {
                    b.Property<Guid>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("BdI_Alu_PedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BdI_Usu_AlumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Enfermedades")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("GradoEscolar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoMatricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(528)
                        .HasColumnType("nvarchar(528)");

                    b.Property<string>("aMaterno")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("aPaterno")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("IdAlumno");

                    b.HasIndex("BdI_Alu_PedId");

                    b.HasIndex("BdI_Usu_AlumId");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Eatech.Models.Bd_Comida", b =>
                {
                    b.Property<Guid>("IDComida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BdI_Com_PedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Porciones")
                        .HasColumnType("int");

                    b.Property<int>("PorcionesDisponibles")
                        .HasColumnType("int");

                    b.Property<string>("Visibilidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDComida");

                    b.HasIndex("BdI_Com_PedId");

                    b.ToTable("Comidas");
                });

            modelBuilder.Entity("Eatech.Models.Bd_Ex_ClaveLicenciaVerifi", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Clave");

                    b.ToTable("LicenciaUsu");
                });

            modelBuilder.Entity("Eatech.Models.Bd_Ex_LicenciaAdmin", b =>
                {
                    b.Property<Guid>("IdLicencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaveLicencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdLicencia");

                    b.HasIndex("ClaveLicencia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LicenciaAdmin");
                });

            modelBuilder.Entity("Eatech.Models.Bd_Pedido", b =>
                {
                    b.Property<Guid>("pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BdI_Alu_PedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BdI_Com_PedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCPedido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotaPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pedido");

                    b.HasIndex("BdI_Alu_PedId");

                    b.HasIndex("BdI_Com_PedId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Eatech.Models.Bd_Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BdI_Usu_AlumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CaducidadToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TokenDRestauracion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("aMaterno")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("nvarchar(28)");

                    b.Property<string>("aPaterno")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("nvarchar(28)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("BdI_Usu_AlumId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Eatech.Models.BdI_Alu_Ped", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAlumno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("pedido")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("pedido");

                    b.ToTable("Intermedia_Alum_Pedi");
                });

            modelBuilder.Entity("Eatech.Models.BdI_Com_Ped", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDComida")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("pedido")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IDComida");

                    b.HasIndex("pedido");

                    b.ToTable("Intermedia_Comida_Pedi");
                });

            modelBuilder.Entity("Eatech.Models.BdI_Usu_Alum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAlumno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Intermedia_Usuario_Alumno");
                });

            modelBuilder.Entity("Eatech.Models.Bd_Alumno", b =>
                {
                    b.HasOne("Eatech.Models.BdI_Alu_Ped", null)
                        .WithMany("alumnos")
                        .HasForeignKey("BdI_Alu_PedId");

                    b.HasOne("Eatech.Models.BdI_Usu_Alum", null)
                        .WithMany("alumno")
                        .HasForeignKey("BdI_Usu_AlumId");
                });

            modelBuilder.Entity("Eatech.Models.Bd_Comida", b =>
                {
                    b.HasOne("Eatech.Models.BdI_Com_Ped", null)
                        .WithMany("Comida")
                        .HasForeignKey("BdI_Com_PedId");
                });

            modelBuilder.Entity("Eatech.Models.Bd_Ex_LicenciaAdmin", b =>
                {
                    b.HasOne("Eatech.Models.Bd_Ex_ClaveLicenciaVerifi", "ClaveNavigation")
                        .WithMany()
                        .HasForeignKey("ClaveLicencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eatech.Models.Bd_Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("ClaveNavigation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Eatech.Models.Bd_Pedido", b =>
                {
                    b.HasOne("Eatech.Models.BdI_Alu_Ped", null)
                        .WithMany("pedidos")
                        .HasForeignKey("BdI_Alu_PedId");

                    b.HasOne("Eatech.Models.BdI_Com_Ped", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("BdI_Com_PedId");
                });

            modelBuilder.Entity("Eatech.Models.Bd_Usuario", b =>
                {
                    b.HasOne("Eatech.Models.BdI_Usu_Alum", null)
                        .WithMany("usuario")
                        .HasForeignKey("BdI_Usu_AlumId");
                });

            modelBuilder.Entity("Eatech.Models.BdI_Alu_Ped", b =>
                {
                    b.HasOne("Eatech.Models.Bd_Alumno", "Idalumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eatech.Models.Bd_Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idalumno");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Eatech.Models.BdI_Com_Ped", b =>
                {
                    b.HasOne("Eatech.Models.Bd_Comida", "IDcomida")
                        .WithMany()
                        .HasForeignKey("IDComida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eatech.Models.Bd_Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IDcomida");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Eatech.Models.BdI_Usu_Alum", b =>
                {
                    b.HasOne("Eatech.Models.Bd_Alumno", "Idalumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eatech.Models.Bd_Usuario", "IdUsu")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdUsu");

                    b.Navigation("Idalumno");
                });

            modelBuilder.Entity("Eatech.Models.BdI_Alu_Ped", b =>
                {
                    b.Navigation("alumnos");

                    b.Navigation("pedidos");
                });

            modelBuilder.Entity("Eatech.Models.BdI_Com_Ped", b =>
                {
                    b.Navigation("Comida");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Eatech.Models.BdI_Usu_Alum", b =>
                {
                    b.Navigation("alumno");

                    b.Navigation("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
